[package]
name = "dicegame"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4.29"
pretty_env_logger = "0.5.0"
rand = "0.9.2"
rayon = "1.10"
